package com.EG.extremegaming.player;

import java.util.List;

import com.EG.extremegaming.booking.Booking;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "player")

public class Player {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String playerId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String phone;

    @DynamoDBAttribute
    private float hoursPlayed;

    @DynamoDBAttribute
    private List<String> friends;

    @DynamoDBAttribute
    private List<Booking> allbookings;

    public Player(String name, String phone, float hoursPlayed, List<String> friends,
            List<Booking> allbookings) {
        this.name = name;
        this.phone = phone;
        this.hoursPlayed = hoursPlayed;
        this.friends = friends;
        this.allbookings = allbookings;
    }

    // @DynamoDBIgnore
    public String getPlayerId() {
        return playerId;
    }

    public void setPlayerId(String playerId) {
        this.playerId = playerId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public float getHoursPlayed() {
        return hoursPlayed;
    }

    public void setHoursPlayed(float hoursPlayed) {
        this.hoursPlayed = hoursPlayed;
    }

    public List<String> getFriends() {
        return friends;
    }

    public void setFriends(List<String> friends) {
        this.friends = friends;
    }

}
